### ISSUE TITLE
New ability 

### ISSUE THREAD

**Issue by DenKey** [vdovinanton/ChatRoom.Web#1]
Hello. Thanks for application. It's very help for me create our internal chat  in network of our company. But has one thing that we need. Please add ability [грабить корованы](http://lurkmore.to/Корованы)  it's will be very cool for us.

Best Regards Den Key

**Comment by vdovinanton** [comment]
Dear @DenKey, thanks for u feedback, Im glad u liked the app, I will do everything possible that would make the caravans, but all elves were eaten by the orcs :angry: maybe you can find some for me?
